DROP DATABASE MYSTIC;

CREATE DATABASE MYSTIC;

USE MYSTIC;

CREATE TABLE IF NOT EXISTS `MYSTIC`.`MOCK` (
  `MOCK_ID` INT NOT NULL AUTO_INCREMENT,
  `MOCK_KEY` LONGTEXT NOT NULL,
  `MOCK_VALUE` LONGTEXT NOT NULL,
  `MOCK_CONTENT_TYPE` TEXT NOT NULL,
  PRIMARY KEY (`MOCK_ID`));

INSERT INTO MOCK VALUES (null, '/mystic', '{\"name\":\"Mystic Mock Server\"}', 'application/json')